package org.csu.sm.domain;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by ltaoj on 2017/8/11.
 */
public class Constant {

    public static List<String> getColleges() {
        List<String> collegeList = new ArrayList<String>();
        collegeList.add("安全工程");
        collegeList.add("材料国际");
        collegeList.add("材料化学");
        collegeList.add("材料科学与工程");
        collegeList.add("财务管理");
        collegeList.add("采矿工程");
        collegeList.add("测绘工程");
        collegeList.add("测控技术与仪器");
        collegeList.add("产品设计");
        collegeList.add("车辆工程");
        collegeList.add("城市地下空间工程");
        collegeList.add( "城乡规划");
        collegeList.add("地理信息科学");
        collegeList.add("地球物理学");
        collegeList.add("地质工程");
        collegeList.add( "电气工程及其自动化");
        collegeList.add("电子商务");
        collegeList.add("电子信息工程");
        collegeList.add("电子信息科学与技术");
        collegeList.add("法学");
        collegeList.add("法医学");
        collegeList.add("法语");
        collegeList.add("粉体材料科学与工程");
        collegeList.add("高分子材料与工程");
        collegeList.add("工程管理");
        collegeList.add("工程力学");
        collegeList.add("工商管理");
        collegeList.add( "工商管理（高水平运动）");
        collegeList.add( "光电信息科学与工程");
        collegeList.add("广播电视学");
        collegeList.add( "国际经济与贸易");
        collegeList.add("汉语言文学");
        collegeList.add("航空航天工程");
        collegeList.add("护理学");
        collegeList.add( "化学工程与工艺");
        collegeList.add( "环境工程");
        collegeList.add( "环境设计");
        collegeList.add("会计学");
        collegeList.add( "基础医学");
        collegeList.add( "机械设计制造及其自动化");
        collegeList.add("计算机科学与技术");
        collegeList.add("建筑环境与能源应用工程");
        collegeList.add("建筑学");
        collegeList.add( "交通设备与控制工程");
        collegeList.add("交通运输");
        collegeList.add( "金融学");
        collegeList.add( "精神医学");
        collegeList.add("口腔医学(五年制)");
        collegeList.add( "口腔医学（5+3）");
        collegeList.add( "矿物加工工程");
        collegeList.add( "劳动与社会保障");
        collegeList.add("理工预科");
        collegeList.add("临床医学(八年)");
        collegeList.add("临床医学(五年制)");
        collegeList.add( "麻醉学");
        collegeList.add( "能源与动力工程");
        collegeList.add("日语");
        collegeList.add("软件工程");
        collegeList.add("社会学");
        collegeList.add( "生物技术");
        collegeList.add( "生物科学");
        collegeList.add( "生物信息学");
        collegeList.add( "生物医学工程");
        collegeList.add("市场营销");
        collegeList.add( "视觉传达设计");
        collegeList.add( "数据科学与大数据技术");
        collegeList.add("数学与应用数学");
        collegeList.add( "数字出版");
        collegeList.add( "思想政治教育");
        collegeList.add("探测制导与控制技术");
        collegeList.add( "铁道工程");
        collegeList.add("通信工程");
        collegeList.add( "统计学");
        collegeList.add("土木工程");
        collegeList.add("土木国际");
        collegeList.add("微电子科学与工程");
        collegeList.add( "文史预科");
        collegeList.add( "无机非金属材料工程");
        collegeList.add( "舞蹈表演");
        collegeList.add("物联网工程");
        collegeList.add("物流工程");
        collegeList.add("西班牙语");
        collegeList.add( "消防工程");
        collegeList.add( "新能源材料与器件");
        collegeList.add( "新能源科学与工程");
        collegeList.add("信息安全");
        collegeList.add( "信息管理与信息系统");
        collegeList.add( "信息与计算科学");
        collegeList.add("行政管理");
        collegeList.add("遥感科学与技术");
        collegeList.add( "药学");
        collegeList.add("冶金工程");
        collegeList.add("医学检验技术");
        collegeList.add("音乐表演");
        collegeList.add( "英语");
        collegeList.add( "应用化学");
        collegeList.add("应用物理学");
        collegeList.add( "预防医学");
        collegeList.add("运动训练");
        collegeList.add("制药工程");
        collegeList.add( "智能科学与技术");
        collegeList.add("资源勘查工程");
        collegeList.add("自动化");
        return collegeList;
    }
}
